export default {
	ACTIONS_WRAPPER_CLASSNAME: 'question-actions',
	APP_WRAPPER_CLASSNAME: 'app-wrapper',
	BACK_BUTTON_CLASSNAME: 'button-back',
	BUTTON_CLASSNAME: 'btn',
	CHECKBOX_INPUT_CLASSNAME: 'checkbox-wrapper--input',
	CHECKBOX_LABEL_CLASSNAME: 'checkbox-wrapper--label',
	CHECKBOX_WRAPPER_CLASSNAME: 'checkbox-wrapper',
	CHECKBOXES_WRAPPER_CLASSNAME: 'checkboxes-wrapper',
	CONTENT_WRAPPER_CLASSNAME: 'content-wrapper',
	FORM_CLASSNAME: 'question-form',
	NEXT_BUTTON_CLASSNAME: 'button-next',
	PAGE_HEADING_CLASSNAME: 'page-heading',
	PAGE_WRAPPER_CLASSNAME: 'page-wrapper',
	PROGRESS_NUMBER_WRAPPER_CLASSNAME: 'progress-number',
	SEGMENTED_SLIDER_INPUT_CLASSNAME: 'segmented-slider--input',
	SEGMENTED_SLIDER_LABEL_CLASSNAME: 'segmented-slider--label',
	SEGMENTED_SLIDER_LABEL_LIST_CLASSNAME: 'segmented-slider--label-list',
	SEGMENTED_SLIDER_LABEL_LIST_ITEM_CLASSNAME: 'segmented-slider--label-list-item',
	SEGMENTED_SLIDER_WRAPPER_CLASSNAME: 'segmented-slider',
}
